cache: yarn
language:
  node_js
node_js:
  - 14
install:
  - npm install -g codecov
script:
  - yarn --frozen-lockfile
  - yarn test && codecov
  - yarn build
# Script that is run after the script success
after_success:
  - yarn build-storybook
deploy:
  provider: pages # Tell Travis we want to deploy to Github Pages
  skip-cleanup: true 
  github-token: $GITHUB_TOKEN # Will take the environment variable you created on step 5
  local_dir: storybook-static # The folder that needs to be deployed
  repo: eGroupAI/egroup-material # Add your username/project_name here
  target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
  on:
    branch: master # Tell Travis to trigger a deploy only when we push to master